### ISSUE TITLE
Flesh Out Scene-Viewer Into Standalone Application

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#211]
Currently scene-viewer is a pretty hacky program mainly designed for testing out rend3. There are a couple things that should be improved to help make it more useful, and make the tool more usable to more people.

It would be neat to publish this as `scene-viewer` or something on crates.

- [x] Command Line Help
- [x] More Command Line Options
- [ ] Default `env_logger` to have `rend3*` at `INFO`
- [ ] Debug Menu (relies on #192)
  - [ ] Load/Unload Gltf Scene (see https://github.com/PolyMeilex/rfd for a way to do this)
  - [ ] Show loading progress.
  - [ ] Framerate/timings
  - [ ] Mesh/Texture/Material/Object Count
  - [ ] Control ambient/directional lights
- [ ] Integration with https://github.com/EmbarkStudios/puffin
  - [ ] Renderer stats (?)
